version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    environment:
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    stdin_open: true  # Keep stdin open for `docker-compose run` access
    tty: true         # Enable TTY for interactive shell access

volumes:
  db_data:
    driver: local
